[package]
name = "kafka-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rdkafka = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
