version: '3.1'

services:
  api:
    build: .
    container_name: api
    volumes:
      - .:/rust/src
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"

  db:
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: deliver_rs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 20
